from django.db import models
from django.utils.translation import ugettext_lazy as _

# Create your models here.

class LegacyMain(models.Model):

    name_L0 = models.CharField(max_length=255, verbose_name=_('Name'))
    price_brutto = models.DecimalField(max_digits=6,decimal_places=2)
    vat = models.DecimalField(max_digits=2,decimal_places=2)
    active = models.BooleanField(default=False)
    xml_description_L0 = models.TextField()
 
    class Meta:
        db_table = "main"

# CREATE TABLE  `mikran_1`.`main` (
#   `id` mediumint(9) NOT NULL auto_increment,
#   `user_id` varchar(255) default NULL,
#   `photo` varchar(255) default NULL,
#   `xml_description_L0` text,
#   `xml_description_L1` text,
#   `xml_description_L2` text,
#   `xml_description_L3` text,
#   `xml_description_L4` text,
#   `xml_short_description_L0` text,
#   `xml_short_description_L1` text,
#   `xml_short_description_L2` text,
#   `xml_short_description_L3` text,
#   `xml_short_description_L4` text,
#   `xml_options` text,
#   `promotion` char(1) default NULL,
#   `newcol` char(1) default NULL,
#   `bestseller` char(1) default NULL,
#   `main_page` char(1) default NULL,
#   `active` char(1) default NULL,
#   `date_update` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
#   `date_add` timestamp NOT NULL default '0000-00-00 00:00:00',
#   `name_L0` varchar(255) default NULL,
#   `name_L1` varchar(255) default NULL,
#   `name_L2` varchar(255) default NULL,
#   `name_L3` varchar(255) default NULL,
#   `name_L4` varchar(255) default NULL,
#   `id_producer` int(11) default NULL,
#   `producer` varchar(255) default NULL,
#   `id_category1` int(11) default NULL,
#   `category1` text,
#   `id_category2` int(11) default NULL,
#   `category2` text,
#   `id_category3` int(11) default NULL,
#   `category3` text,
#   `id_category4` int(11) default NULL,
#   `category4` text,
#   `id_category5` int(11) default NULL,
#   `category5` text,
#   `price_brutto` double default NULL,
#   `id_currency` int(11) default NULL,
#   `vat` int(11) default NULL,
#   `price_brutto_detal` double default NULL,
#   `id_available` mediumint(9) default '0',
#   `price_brutto_2` double default NULL,
#   `hidden_price` mediumint(9) default '0',
#   `discount` double default NULL,
#   `accessories` text,
#   `onet_category` text,
#   `price_currency` double default NULL,
#   `url` text,
#   `user_score` float default NULL,
#   `max_discount` float default NULL,
#   `onet_export` int(11) default '0',
#   `onet_status` int(11) default '1',
#   `onet_image_export` int(11) default '1',
#   `onet_image_desc` varchar(255) default NULL,
#   `onet_image_title` varchar(255) default NULL,
#   `onet_attrib` varchar(255) default NULL,
#   `onet_attr` varchar(255) default NULL,
#   `main_keys_online` int(11) default '0',
#   `flash` varchar(255) default NULL,
#   `pdf` varchar(255) default NULL,
#   `flash_html` text,
#   `google_title` varchar(255) NOT NULL default '',
#   `google_keywords` varchar(255) NOT NULL default '',
#   `google_description` varchar(255) NOT NULL default '',
#   `category_multi_1` varchar(255) NOT NULL default '',
#   `category_multi_2` varchar(255) NOT NULL default '',
#   `id_category_multi_1` varchar(255) NOT NULL default '',
#   `id_category_multi_2` varchar(255) NOT NULL default '',
#   `ask4price` char(1) NOT NULL default '',
#   `wp_export` int(11) NOT NULL default '0',
#   `status_vat` int(11) default '0',
#   `weight` float default '0',
#   `id_shop` int(11) default '0',
#   `interia_export` int(11) NOT NULL default '0',
#   `doc` varchar(255) default NULL,
#   `link_url` text,
#   `link_name` text,
#   `ranking` longtext,
#   `points` char(1) NOT NULL default '0',
#   `points_value` int(9) NOT NULL default '0',
#   `ceneo_export` smallint(6) NOT NULL default '1',
#   `sms` smallint(6) NOT NULL default '0',
#   `item_checked` char(1) default NULL,
#   PRIMARY KEY  (`id`),
#   KEY `main_id_category1_idx` (`id_category1`),
#   KEY `main_id_category2_idx` (`id_category2`),
#   KEY `main_id_category3_idx` (`id_category3`),
#   KEY `main_id_category4_idx` (`id_category4`),
#   KEY `main_id_category5_idx` (`id_category5`),
#   KEY `main_id_producer_idx` (`id_producer`),
#   KEY `main_producer` (`producer`),
#   KEY `main_name_idx` (`name_L0`),
#   KEY `main_price_brutto_idx` (`price_brutto`),
#   KEY `main_promotion_idx` (`promotion`),
#   KEY `main_newcol_idx` (`newcol`),
#   KEY `main_main_page_idx` (`main_page`),
#   KEY `main_bestseller_idx` (`bestseller`),
#   KEY `photo` (`photo`),
#   KEY `user_id` (`user_id`),
#   KEY `category_multi_1` (`category_multi_1`),
#   KEY `category_multi_2` (`category_multi_2`),
#   KEY `id_category_multi_2` (`id_category_multi_2`),
#   KEY `id_category_multi_1` (`id_category_multi_1`),
#   KEY `en_name` (`name_L1`),
#   KEY `de_name` (`name_L2`),
#   KEY `id_shop` (`id_shop`),
#   KEY `name_L3` (`name_L3`),
#   KEY `name_L4` (`name_L4`),
#   FULLTEXT KEY `xml_description` (`xml_description_L0`,`xml_short_description_L0`),
#   FULLTEXT KEY `en_xml_description` (`xml_description_L1`),
#   FULLTEXT KEY `de_xml_description` (`xml_description_L2`),
#   FULLTEXT KEY `en_xml_short_description` (`xml_short_description_L1`),
#   FULLTEXT KEY `de_xml_short_description` (`xml_short_description_L2`)
# ) ENGINE=MyISAM AUTO_INCREMENT=9851 DEFAULT CHARSET=latin2
